# echo 'change-me' > uptime_password.txt
services:
  uptime:
    image: ghcr.io/rubyrackgames/uptime-server:latest
    container_name: uptime
    restart: unless-stopped
    stop_grace_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "27016:27016/udp"
    volumes:
      - uptime-data:/data
    environment:
      UPTIME_NAME: My Datacenter
      UPTIME_PASSWORD_FILE: /run/secrets/uptime_password
    secrets:
      - uptime_password

secrets:
  uptime_password:
    file: ../uptime_password.txt

volumes:
  uptime-data:
